#!/usr/bin/env sh

if ! type "nix" > /dev/null; then
  echo "Minifedi requires Nix. Please install it from your package manager, or following the instructions at https://nixos.org/download.html."
  exit 1
fi

subcommand=$1
shift

if [ -z "$subcommand" ]; then
  echo "subcommand required: start, install-cert, mk-mastodon"
  exit 1
fi

nix --extra-experimental-features "flakes nix-command" run .#$subcommand -- $@
