# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches }: let
  src = fetchFromGitHub {
    owner = "mastodon";
    repo = "mastodon";
    rev = "a40529fa79c6882eb1929014e5f9324d8e81ae49";
    sha256 = "/b7Z5WbErerqRb5nHh57mbjOyP7tDpi4KUglXdd693Y=";
  };
in applyPatches {
  inherit src;
  patches = [];
}
