# This file was generated by minifedi mk-mastodon.
{ fetchgit, applyPatches }: fetchgit {
    url = "https://github.com/Mastodon/Mastodon.git";
    rev = "v4.1.4";
    sha256 = "170xjvd5m6cmlamq0pw3nd3dnxjcmmvxw5yqwp11rh0xq8xw2hpi";
}
