# This file was generated by minifedi mk-mastodon.
{ fetchgit, applyPatches }: fetchgit {
    url = "https://github.com/glitch-soc/Mastodon.git";
    rev = "a004718";
    sha256 = "09i3y408dv5bp1axqnn1v25yg5l9hqj85x524bai5a186wh0pcqh";
}
